/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.user.repository.jooq;


import com.petromirdzhunev.user.repository.jooq.tables.AuthUserDbTable;
import com.petromirdzhunev.user.repository.jooq.tables.AuthUserRoleDbTable;
import com.petromirdzhunev.user.repository.jooq.tables.AuthUserRolesDbTable;
import com.petromirdzhunev.user.repository.jooq.tables.VehicleDbTable;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:AE08384C8C22DC03C779B0E0AF894D04",
        "schema version:vehicle_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.auth_user</code>.
     */
    public static final AuthUserDbTable AUTH_USER_DB_TABLE = AuthUserDbTable.AUTH_USER_DB_TABLE;

    /**
     * The table <code>public.auth_user_role</code>.
     */
    public static final AuthUserRoleDbTable AUTH_USER_ROLE_DB_TABLE = AuthUserRoleDbTable.AUTH_USER_ROLE_DB_TABLE;

    /**
     * The table <code>public.auth_user_roles</code>.
     */
    public static final AuthUserRolesDbTable AUTH_USER_ROLES_DB_TABLE = AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE;

    /**
     * The table <code>public.vehicle</code>.
     */
    public static final VehicleDbTable VEHICLE_DB_TABLE = VehicleDbTable.VEHICLE_DB_TABLE;
}
