/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.users.repository.jooq.tables;


import com.petromirdzhunev.users.repository.jooq.Indexes;
import com.petromirdzhunev.users.repository.jooq.Keys;
import com.petromirdzhunev.users.repository.jooq.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3",
        "schema version:Init.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthUserRoleDbTable extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.auth_user_role</code>
     */
    public static final AuthUserRoleDbTable AUTH_USER_ROLE_DB_TABLE = new AuthUserRoleDbTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.auth_user_role.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.auth_user_role.code</code>.
     */
    public final TableField<Record, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.auth_user_role.name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private AuthUserRoleDbTable(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private AuthUserRoleDbTable(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.auth_user_role</code> table reference
     */
    public AuthUserRoleDbTable(String alias) {
        this(DSL.name(alias), AUTH_USER_ROLE_DB_TABLE);
    }

    /**
     * Create an aliased <code>public.auth_user_role</code> table reference
     */
    public AuthUserRoleDbTable(Name alias) {
        this(alias, AUTH_USER_ROLE_DB_TABLE);
    }

    /**
     * Create a <code>public.auth_user_role</code> table reference
     */
    public AuthUserRoleDbTable() {
        this(DSL.name("auth_user_role"), null);
    }

    public <O extends Record> AuthUserRoleDbTable(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, AUTH_USER_ROLE_DB_TABLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUTH_USER_ROLE_PKEY);
    }

    @Override
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.AUTH_USER_ROLE_PKEY;
    }

    @Override
    public AuthUserRoleDbTable as(String alias) {
        return new AuthUserRoleDbTable(DSL.name(alias), this);
    }

    @Override
    public AuthUserRoleDbTable as(Name alias) {
        return new AuthUserRoleDbTable(alias, this);
    }

    @Override
    public AuthUserRoleDbTable as(Table<?> alias) {
        return new AuthUserRoleDbTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRoleDbTable rename(String name) {
        return new AuthUserRoleDbTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRoleDbTable rename(Name name) {
        return new AuthUserRoleDbTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRoleDbTable rename(Table<?> name) {
        return new AuthUserRoleDbTable(name.getQualifiedName(), null);
    }
}
