package com.petromirdzhunev.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import lombok.Builder;
import lombok.Data;

// FIXME: This will be autogenerated from JOOQ
@Builder
@Data
public class Order {
	private Long id;
	private Long customerId;
	private List<Product> products;
	private BigDecimal totalPrice;
	private String status;
	private String currency;
	private LocalDateTime createAt;
	private LocalDateTime updatedAt;
}