package com.petromirdzhunev.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import lombok.Builder;
import lombok.Data;

// FIXME: This will be autogenerated from JOOQ
@Data
@Builder
public class Product {
	private Long id;
	private String name;
	private String description;
	private BigDecimal price;
	private Integer stock;
	private String image;
	private Category category;
	private LocalDateTime createAt;
	private LocalDateTime updatedAt;
}